---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    key_groups:
      - age:
          - age1mwkesnv3t3r28nuge8t45r6gatn2kl9j70y3gj0cefqxygqftsjslukuzt
  - path_regex: cluster/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1mwkesnv3t3r28nuge8t45r6gatn2kl9j70y3gj0cefqxygqftsjslukuzt
