# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:7j1AhjTvrUvY8J9Z3ucyMoT8yE4=,iv:m/E5Xnfjm0Gp6LpKXFcsNiqSG1bLYbzxt2Qi3jBDmLM=,tag:KmQA4268PK96xDupuzOCdw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:f3/9HLezd9hq4t2hgbtUKuqe3DEagPHYIbfA1xiqgSL6aNa4+w==,iv:TnNHsu959gVvAVrzfpuL2vacvY/bsWr/RJGL8vUA+oE=,tag:tbMbMaQGNkcrcAgQumR70g==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:skdZ6rEKNUj1v8JGWwA=,iv:wT/2CMe78fk8Pkkajfg0mvxW9S8lR7ATYzgaDRe7omY=,tag:ohwYZ6srI/Oi6bfzhWDf3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mwkesnv3t3r28nuge8t45r6gatn2kl9j70y3gj0cefqxygqftsjslukuzt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1M1Y5N09rb0VwVExwN0Jv
            TUIyM3l0Q2NvSHNZcnBtNnF0aU1UTm1CNnljClRUR1JqclMxaWlIRUZxTXZhVUhl
            QmFmQ0t4dVNSa2VYNW16ZG5QeVVVc3cKLS0tIDN4ZFl5S1ZoY3pKLzI4cFZES0Vk
            MDVRL3M3Nkl4QmtzR21FemtBaDNXVlkKxF3ZqskNQ54xjuaMTgd270WIgEcAHgTU
            m6tzdBpdiCbapmjP212TKOeQvFbDz+d6vvxIyz/B566LYtOPaN8UxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-03T23:23:29Z"
    mac: ENC[AES256_GCM,data:DIuIAXdH59BBLYJ7IZnJYVoTovNTdrMQk3NqtFFqCt7aCgi4IaF0d8BSh/4bNTQK9azheEART74sQs+cO/OqLkjbfoc46aiDEuN0CJBXg3dJHB8m4cHDlpUddXyZ4EY0tfAF3xHiEwni02RdiTXAv6i6D48JiSHGsDiQMtDo6MQ=,iv:2TnZ8UUKEHjK/nXoNX4meh965vj1Sgm20RmmRdAT+70=,tag:RAG/83oamqdLJlgAlH5nCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
