# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: networking
stringData:
    api-key: ENC[AES256_GCM,data:gTz3xF6/cVmilWGP8AgpAq4e1lU094/3cM9GnFNwx68gWIMMIw==,iv:57UIKBS2d8dsyPD78q5O/5V+FFwgulRLvojcCQCqhbc=,tag:XaFYxelvDVqp1T9vNcRB1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mwkesnv3t3r28nuge8t45r6gatn2kl9j70y3gj0cefqxygqftsjslukuzt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdGdQUFgrT1M0MzJJTXYr
            YTM0dHlMMy92UWlITkxiNTNEbi9yR0RXV2tRCklpdVk3VnRXT1ZCa3dXQjJ1S29o
            NDZYYWVQbkhNZzZ4N3plODFQZkFMTzQKLS0tIGlWa29IRGF3MUFkTmdZTjFMQW84
            UndNNVZ0YXIvYlQ3TTNycUdGblUzRjQKSgXK3h1N84Zn0npOPYG465wTmu2awMti
            8QDi7RBdSTDE3bdvPzwsjtpnNHq8I2P3PjmFVQpqb62XCSyjlXh8Yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-03T23:23:29Z"
    mac: ENC[AES256_GCM,data:PH2hKX6Gk5wlR3U0TNyycCH5aWplDZwvdhy4G1NEhANzyDI+i90mxA8KcgemeL4tiAENwHf4LPGY39PFJo+0gCCSP2EMZdEjVsCN3E/LZMR6PQ/pFRCAxltfFDd556EAohSRanQYWdp1lBgNJoAMH8ETIzzoXdHHBQRNZzzUPL8=,iv:fus5IvzqYTOilXu18cIMUhRQ/aFmdcVSPP6y6+nwkww=,tag:FCphXyL5UN8EVbAq8KMv8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
