# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: networking
stringData:
    api-key: ENC[AES256_GCM,data:AyCxaPE//njvtE7NkWhVQDC+J+seVyYeUWMG4OPbPMumO06zag==,iv:sIvC0dUhffUTnxNxBjl/nQlEqMUyx/ZLN5VCRKQOXj4=,tag:JGRZFvJ2VuQZLzs1a/VnuQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mwkesnv3t3r28nuge8t45r6gatn2kl9j70y3gj0cefqxygqftsjslukuzt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4OHdYaDJuVUZTWTBQWklC
            UlRFaksydjc4azY2ejlrd2Q2N05RZ3E5SGhjCnNHUXBNSCtJS3pzZmw4ejlJMzFS
            OWk3aStmemRvWjR3eHRkYk84R0h5MkEKLS0tIGN6ZGV3eDVGb01kbUVwV0dnV1ZB
            dXl1MlJUaUFSYVBORDZzWi81TXVPa00K+RbvQ15SxIn5TgeqDaCTA7kWDyDb+D7c
            jSaXjUXOeHOgQqHqM6ti7D0Y9qBkqb9H04d6mXtdBrxxRaSfJVDe0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-03T19:05:15Z"
    mac: ENC[AES256_GCM,data:h7aGKNqATReIcRuE60+GJGswpce8JpsMozKS/meXvyxdB6/Fns1qVLo4bzP4fWwH6OnXAwnoWy/kFwLtI1znL9VsZJqyDu41T5tcayP0uOUoU4pB3/CYRz46eFZFk1x18gAZBLBXebA5KhtQqpLQjHXgHIa8yIT3wzOGQfUf0jA=,iv:Z2k2zCSvv2YlraA6VnlZuY+fp6HgnuEPgCDaGmyqzNw=,tag:kULDaAQ2kfiBtQaSbRjcpg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
